import {
  LayoutDashboard,
  GraduationCap,
  Users,
  UserCog,
  ClipboardList,
  Calendar,
  FileText,
  IndianRupee,
  BookOpen,
  MessageSquare,
  Bus,
  Building,
  BarChart3,
  Settings,
  CalendarDays,
} from "lucide-react";

export const MENU = [
  {
    label: "Dashboard",
    icon: LayoutDashboard,
    href: "dashboard",
    isForAll: true,
    permission: "dashboard.view",
  },
  {
    label: "Academics",
    icon: GraduationCap,
    permission: "academic.manage",
    children: [
      { label: "Classes & Sections", href: "academics/classes", permission: "academic.manage" },
      { label: "Subjects", href: "academics/subjects", permission: "academic.manage" },
      { label: "Subject-Teacher Mapping", href: "academics/mapping", permission: "academic.manage" },
      { label: "Streams / Groups", href: "academics/streams", permission: "academic.manage" },
      { label: "Class Promotions Setup", href: "academics/promotions", permission: "academic.manage" },
    ],
  },
  {
    label: "Admissions",
    icon: FileText,
    permission: "admission.manage",
    children: [
      { label: "New Admission", href: "admissions/new", permission: "admission.create" },
      { label: "Enquiry Management", href: "admissions/enquiry", permission: "admission.manage" },
      { label: "Admission Follow-ups", href: "admissions/followups", permission: "admission.manage" },
      { label: "Admission Reports", href: "admissions/reports", permission: "admission.manage" },
      { label: "Import / Export", href: "admissions/import-export", permission: "admission.create" },
    ],
  },
  {
    label: "Students",
    icon: Users,
    permission: "student.view",
    children: [
      { label: "Student Profile", href: "students", permission: "student.view" },
      { label: "Promote / Demote", href: "students/promote", permission: "student.manage" },
      { label: "Assign Roll Numbers", href: "students/rollno", permission: "student.manage" },
      { label: "ID Cards", href: "students/idcards", permission: "student.view" },
    ],
  },
  {
    label: "Employees",
    icon: UserCog,
    permission: "employee.manage",
    children: [
      { label: "Admit Employee", href: "employees/admit", permission: "employee.create" },
      { label: "Employee Profile", href: "employees", permission: "employee.manage" },
      { label: "Employee Attendance", href: "attendance/employees", permission: "employee.manage" },
      { label: "Import / Export", href: "employees/import-export", permission: "employee.manage" },
    ],
  },
  {
    label: "Attendance",
    icon: ClipboardList,
    permission: "attendance.view",
    children: [
      { label: "Mark Attendance", href: "attendance/", permission: "attendance.mark" },
      { label: "Pending Attendance", href: "attendance/pending", permission: "attendance.modify" },
      { label: "Student Attendance", href: "attendance/students", permission: "attendance.view" },
      { label: "Employee Attendance", href: "attendance/employees", permission: "attendance.view" },
    ],
  },
  // {
  //   label: "Fees & Accounts",
  //   icon: IndianRupee,
  //   permission: "fee.view",
  //   children: [
  //     { label: "Fee Heads", href: "fees/heads", permission: "fee.manage" },
  //     { label: "Fee Templates", href: "fees/templates", permission: "fee.manage" },
  //     { label: "Student Fee Assignment", href: "fees/assign", permission: "fee.manage" },
  //     { label: "Fee Dues", href: "fees/dues", permission: "fee.view" },
  //     { label: "Collect Fees", href: "fees/collect", permission: "fee.manage" },
  //     { label: "Receipts", href: "fees/receipts", permission: "fee.view" },
  //     { label: "Refund", href: "fees/refund", permission: "fee.manage" },
  //     { label: "Fee Ledger", href: "fees/ledger", permission: "fee.view" },
  //     { label: "Day Book", href: "finance/daybook", permission: "fee.view" },
  //     { label: "Finance Reports", href: "finance/reports", permission: "fee.view" },
  //   ],
  // },
  {
    label: "Fees & Accounts",
    icon: IndianRupee,
    permission: "fee.view",
    children: [
      {
        label: "Fee Setup",
        children: [
          { label: "Fee Heads", href: "fees/heads", permission: "fee.manage" },
          { label: "Fee Templates", href: "fees/templates", permission: "fee.manage" },
          { label: "Student Fee Assignment", href: "fees/assign", permission: "fee.manage" },
        ],
      },
      {
        label: "Fee Operations",
        children: [
          { label: "Fee Dues", href: "fees/dues", permission: "fee.view" },
          { label: "Collect Fees", href: "fees/collect", permission: "fee.manage" },
          { label: "Receipts", href: "fees/receipts", permission: "fee.view" },
          { label: "Refunds", href: "fees/refund", permission: "fee.manage" },
        ],
      },
      {
        label: "Accounts & Reports",
        children: [
          { label: "Fee Ledger", href: "fees/ledger", permission: "fee.view" },
          { label: "Day Book", href: "finance/daybook", permission: "fee.view" },
          { label: "Finance Reports", href: "finance/reports", permission: "fee.view" },
        ],
      },
  
    ],
  },  
  {
    label: "Learning",
    icon: BookOpen,
    permission: "learning.manage",
    children: [
      { label: "Homework", href: "learning/homework", permission: "learning.manage" },
      { label: "Assignments", href: "learning/assignments", permission: "learning.manage" },
      { label: "Study Materials", href: "learning/materials", permission: "learning.manage" },
      { label: "Submission Tracking", href: "learning/submissions", permission: "learning.manage" },
      { label: "Teacher Lesson Plans", href: "learning/lesson-plans", permission: "learning.manage" },
    ],
  },
  {
    label: "Timetable",
    icon: Calendar,
    permission: "timetable.view",
    children: [
      { label: "View Timetable", href: "timetable/view", permission: "timetable.view" },
      { label: "Edit Timetable", href: "timetable/manage", permission: "timetable.edit" },
      { label: "Timetable Settings", href: "timetable/settings", permission: "timetable.edit" },
      { label: "Substitutions", href: "timetable/substitutions", permission: "timetable.edit" },
      { label: "Temporary Timetable", href: "timetable/temp", permission: "timetable.edit" },
    ],
  },
  {
    label: "Exams & Results",
    icon: BookOpen,
    permission: "exam.manage",
    children: [
      { label: "Exam Terms", href: "exams/terms", permission: "exam.create" },
      { label: "Exam Setup", href: "exams/setup", permission: "exam.create" },
      { label: "Marks Entry", href: "exams/marks", permission: "exam.manage" },
      { label: "Exam Reports", href: "exams/reports", permission: "exam.view" },
    ],
  },
  {
    label: "Communication",
    icon: MessageSquare,
    permission: "communication.manage",
    children: [
      { label: "Noticeboard", href: "communication/noticeboard", permission: "communication.manage" },
      { label: "Class Notice", href: "communication/class", permission: "communication.manage" },
      { label: "Student Messaging", href: "communication/student", permission: "communication.manage" },
      { label: "Templates", href: "communication/templates", permission: "communication.manage" },
    ],
  },
  {
    label: "Leave Portal",
    icon: ClipboardList,
    href: "leave",
    permission: "leave.manage",
  },
  {
    label: "Complaint Portal",
    icon: MessageSquare,
    href: "complaints",
    permission: "complaint.manage",
  },
  {
    label: "Holiday",
    icon: CalendarDays,
    href: "holidays",
    permission: "holiday.view",
  },
  {
    label: "Transport",
    icon: Bus,
    permission: "transport.manage",
    children: [
      { label: "Routes", href: "transport/routes", permission: "transport.manage" },
      { label: "Vehicles", href: "transport/vehicles", permission: "transport.manage" },
      { label: "Drivers", href: "transport/drivers", permission: "transport.manage" },
      { label: "Student Allocation", href: "transport/allocation", permission: "transport.manage" },
      { label: "Transport Fees", href: "transport/fees", permission: "transport.manage" },
    ],
  },
  {
    label: "Hostel",
    icon: Building,
    permission: "hostel.manage",
    children: [
      { label: "Hostels", href: "hostel/list", permission: "hostel.manage" },
      { label: "Rooms", href: "hostel/rooms", permission: "hostel.manage" },
      { label: "Student Allocation", href: "hostel/allocation", permission: "hostel.manage" },
      { label: "Hostel Attendance", href: "hostel/attendance", permission: "hostel.manage" },
      { label: "Hostel Fees", href: "hostel/fees", permission: "hostel.manage" },
    ],
  },
  {
    label: "Reports & Analytics",
    icon: BarChart3,
    permission: "report.view",
    children: [
      { label: "Student Reports", href: "reports/students", permission: "report.view" },
      { label: "Attendance Reports", href: "reports/attendance", permission: "report.view" },
      { label: "Fee Reports", href: "reports/fees", permission: "report.view" },
      { label: "Exam Reports", href: "reports/exams", permission: "report.view" },
      { label: "Payroll Reports", href: "reports/payroll", permission: "report.view" },
      { label: "Teacher Workload", href: "reports/workload", permission: "report.view" },
      { label: "Class Performance", href: "reports/performance", permission: "report.view" },
      { label: "Export Reports", href: "reports/export", permission: "report.view" },
    ],
  },
  {
    label: "System Settings",
    icon: Settings,
    permission: "system.manage",
    children: [
      { label: "School Profile", href: "system/profile", permission: "system.manage" },
      { label: "Academic Settings", href: "system/academic", permission: "system.manage" },
      { label: "Roles & Permissions", href: "system/roles", permission: "system.manage" },
      { label: "Import / Export", href: "system/import-export", permission: "system.manage" },
      { label: "Audit Logs", href: "system/audit", permission: "system.manage" },
      { label: "App Settings", href: "system/app", permission: "system.manage" },
    ],
  },
];
