import { SuperAdminProvider } from "@/context/SuperAdminContext";
import "../globals.css";
import AdminShell from "@/components/admin/AdminShell";

export const metadata = {
  title: "Admin - Appitor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SuperAdminProvider>
      <AdminShell>
        {children}
      </AdminShell>
    </SuperAdminProvider>
  );
}
