import { SuperAdminProvider } from "@/context/SuperAdminContext";
import "../globals.css";

export const metadata = {
  title: "Admin - Appitor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SuperAdminProvider>
      {children}
    </SuperAdminProvider>
  );
}
