import { SuperAdminProvider } from "@/context/SuperAdminContext";
import AdminShell from "@/components/admin/AdminShell";

export const metadata = {
  title: "Admin - Appitor",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <SuperAdminProvider>
      <AdminShell>
        {children}
      </AdminShell>
    </SuperAdminProvider>
  );
}
